In [ ]:
import numpy as np
import heapq # Importing Priority Queue

In [ ]:
# Initial State
init = np.array([
    [1, 2, 3],
    [4, 0, 6],
    [7, 5, 8]
])
# Required Goal State
final = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])

In [ ]:
# State class to store info about a state
class State:
    def __init__(self, state, x, y, cost, parent = None):
        self.state = state
        self.x = x
        self.y = y
        self.cost = cost
        self.parent = parent

    def __lt__(self, other):
        return (self.state < other.state).any()

In [ ]:
# Finding 0 in start state
start_x, start_y = np.where(np.array(init) == 0)
start = State(init, start_x[0], start_y[0], 0)

In [ ]:
# Helper Functions for swapping in states
def swap_up(node):
    state = node.state.copy()
    x = node.x
    y = node.y
    state[x][y], state[x - 1][y] = state[x - 1][y], state[x][y]
    x = x - 1
    return State(state, x, y, node.cost + 1, node)

def swap_down(node):
    state = node.state.copy()
    x = node.x
    y = node.y
    state[x][y], state[x + 1][y] = state[x + 1][y], state[x][y]
    x = x + 1
    return State(state, x, y, node.cost + 1, node)

def swap_left(node):
    state = node.state.copy()
    x = node.x
    y = node.y
    state[x][y], state[x][y - 1] = state[x][y - 1], state[x][y]
    y = y - 1
    return State(state, x, y, node.cost + 1, node)

def swap_right(node):
    state = node.state.copy()
    x = node.x
    y = node.y
    state[x][y], state[x][y + 1] = state[x][y + 1], state[x][y]
    y = y + 1
    return State(state, x, y, node.cost + 1, node)

In [ ]:
# Helper Function for finding visited states
def find_in_open_closed(node, open, closed):
    for i in open:
        if (i[1].state == node.state).all() and i[1].cost > node.cost:
            i[1].cost = node.cost
            i[1].parent = node.parent
            return True

    pos = -1
    for i in range(len(closed)):
        if (closed[i].state == node.state).all():
            pos = i
            break
    if pos >= 0 and closed[i].cost > node.cost:
        n = closed.pop(i)
        n.cost = node.cost
        n.parent = node.parent
        heapq.heappush(open, (n.cost, n))
        return True

    return False

In [ ]:
# Processing a state including finding its neighbours and adding them to open
def find_neighbours(node, open, closed):
    if node.x < 2:
        new_node = swap_down(node)
        if not find_in_open_closed(new_node, open, closed):
            heapq.heappush(open, (new_node.cost, new_node))

    if node.x > 0:
        new_node = swap_up(node)
        if not find_in_open_closed(new_node, open, closed):
            heapq.heappush(open, (new_node.cost, new_node))

    if node.y < 2:
        new_node = swap_right(node)
        if not find_in_open_closed(new_node, open, closed):
            heapq.heappush(open, (new_node.cost, new_node))

    if node.y > 0:
        new_node = swap_left(node)
        if not find_in_open_closed(new_node, open, closed):
            heapq.heappush(open, (new_node.cost, new_node))

In [ ]:
# Helper Function to print path from start to goal
def print_path(goal):
    path = [goal]
    while not (path[0].state == init).all():
        path.insert(0, path[0].parent)
    print("\n\tPath:- \n")
    for i in path:
        print(i.state, end = "\n\n")

In [ ]:
def uniform_cost_search():
    open = [(0, start)]  # Priority queue with (cost, state) tuples
    closed = []
    found_goal = False

    max_mem = 0 # save maximum memory usage

    while len(open):
        max_mem = max(max_mem, len(open) + len(closed))
        _, n = heapq.heappop(open)
        print(n.state, n.cost)
        closed.append(n)

        find_neighbours(n, open, closed)
        if (n.state == final).all(): # If goal is found, path is printed
            found_goal = True
            print_path(n)
            break

    return {"Goal Found": found_goal != False, "Memory Usage (maximum states stored)": max_mem, "Time Taken (nodes visited)": len(closed)}

In [ ]:
print(uniform_cost_search())

[[1 2 3]
 [4 5 6]
 [7 8 0]] 0

	Path:- 

[[1 2 3]
 [4 5 6]
 [7 8 0]]

{'Goal Found': True, 'Memory Usage (maximum states stored)': 1, 'Time Taken (nodes visited)': 1}
